In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import os

path = os.getcwd()
travel_data = pd.read_csv(path + '/Data/trip_plan.csv', encoding = 'latin1') 
#travel_data = travel_data[travel_data['lat'] != -999]

In [4]:
travel_data
recommented_attraction = travel_data.iloc[:12, :]
recommented_attraction
#travel_data

address  \
0          1000 5th Ave, New York City, NY 10028-0198   
1                                   New York City, NY   
2   420 W 14th St, Floor 2, New York City, NY 1001...   
3   59th to 110th Street, Manhattan Borough, from ...   
4   180 Greenwich St, World Trade Center, New York...   
5            30 Rockefeller Center, New York City, NY   
6   350 Fifth Avenue, Between 33rd and 34th Street...   
7                             New York City, NY 10014   
8                   Broadway, New York City, NY 10036   
9      89 E 42nd Street, New York City, NY 10017-5503   
10            Liberty Island, New York City, NY 10004   
11                                  New York City, NY   

                                          description  \
0   At New York City's most visited museum and att...   
1                                                -999   
2   Ground Zero Museum Workshop: Images & Artifact...   
3   For more than 150 years, visitors have flocked...   
4   The National September 11 Memorial & Museum is...   
5   Top of the Rock Observation Deck, the newly op...   
6   The world-famous Empire State Building offers ...   
7   The High Line is an elevated railway transform...   
8   Central area in NYC that has many shops, resta...   
9   Grand Central Terminal is the most extraordina...   
10  The Statue of Liberty Enlightening the World w...   
11  Description: The most famous theater district ...   

                                               detail        lat        lng  \
0   Recommended length of visit: 2-3 hours   Fee: Yes  40.779430 -73.963240   
1                                                -999  40.748330 -73.985680   
2              Recommended length of visit: 1-2 hours  40.742065 -74.002530   
3   Recommended length of visit: More than 3 hours...  40.783005 -73.965360   
4    Recommended length of visit: 1-2 hours   Fee: No  40.711510 -74.013320   
5                                            Fee: Yes  40.758884 -73.979385   
6   Recommended length of visit: 1-2 hours   Fee: Yes  40.748135 -73.984800   
7    Recommended length of visit: 2-3 hours   Fee: No  40.739437 -74.008300   
8              Recommended length of visit: 1-2 hours  40.758890 -73.985120   
9              Recommended length of visit: 1-2 hours  40.752728 -73.977230   
10  Recommended length of visit: More than 3 hours...  40.689760 -74.045135   
11                                               -999  40.757970 -73.985535   

                                   name  rating  total_review  
0        The Metropolitan Museum of Art     5.0         38595  
1                     Manhattan Skyline     5.0         15397  
2           Ground Zero Museum Workshop     5.0          2619  
3                          Central Park     4.5         86871  
4   The National 9/11 Memorial & Museum     4.5         57149  
5      Top of the Rock Observation Deck     4.5         54110  
6                 Empire State Building     4.5         48946  
7                         The High Line     4.5         39757  
8                          Times Square     4.5         28260  
9                Grand Central Terminal     4.5         26290  
10                    Statue of Liberty     4.5         24861  
11                             Broadway     4.5         21593

In [27]:
f = open('myfile','w')
for t in range(3):
#index_list.append(labels[labels == i].tolist())
    f.write('Day '+ str(t) + '\n')
    f.write('Attractions: ' + '\n')
    for x in index_list[t]:
        f.write(recommented_attraction.iloc[x]['name'] + '\n')
        f.write(recommented_attraction.iloc[x]['address'] + '\n')
        f.write(recommented_attraction.iloc[x]['description'] + '\n')
        f.write(recommented_attraction.iloc[x]['detail'] + '\n\n')

In [35]:
recommendation_order = np.random.permutation(3)
recommendation_order[3]
recommented_center = center_points[recommendation_order, :]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [44]:
"""
cordinate_data1 = np.array(travel_data['lat'])
cordinate_data2 = np.array(travel_data['lng'])
"""
from sklearn.cluster import KMeans
cordinate_data = []
recommented_attraction = travel_data.iloc[:12, :]
for i in range(recommented_attraction.shape[0]):
    temp = []
    temp.append(recommented_attraction['lat'].iloc[i])
    temp.append(recommented_attraction['lng'].iloc[i])
    cordinate_data.append(temp)
    
recommendation_order = np.random.permutation(3)

kmeans = KMeans(n_clusters=3, random_state=0).fit(cordinate_data)

center_points = kmeans.cluster_centers_

recommented_center =kmeans.cluster_centers_[recommendation_order, :]
index_list = {}
a = pd.Series(kmeans.labels_)
for i in range(3):
    index_list[i] = (a[a == i].index.tolist())
"""
print(index_list)
print(len(a[a==4]))
print(kmeans.labels_)
b = np.asarray(cordinate_data)
print(type(kmeans.labels_))
print(type(kmeans.cluster_centers_))
"""
order_list = sorted(index_list, key=lambda k: len(index_list[k]), reverse = True)
order_list


index_list, center_points = f(index_list, order_list, cordinate_data, center_points)
center_points = np.asarray(center_points)
print(center_points)
recommented_center = center_points[recommendation_order, :]
print(center_points)

[[ 40.76851325 -73.9727375 ]
 [ 40.72466925 -74.0130725 ]
 [ 40.7493535  -73.98809875]]
[[ 40.76851325 -73.9727375 ]
 [ 40.72466925 -74.0130725 ]
 [ 40.7493535  -73.98809875]]


In [36]:
kmeans.cluster_centers_

array([[ 40.7812175 , -73.9643    ],
       [ 40.700635  , -74.0292275 ],
       [ 40.75080488, -73.9885725 ]])

In [37]:
center_points

array([[ 40.7812175 , -73.9643    ],
       [ 40.700635  , -74.0292275 ],
       [ 40.75080488, -73.9885725 ]])

In [21]:
index_list, a = f(index_list, order_list, cordinate_data, center_points)

In [22]:
a

[[40.768513249999998, -73.972737499999994],
 [40.724669249999998, -74.013072499999993],
 [40.749353499999998, -73.988098750000006]]

In [15]:
center_points

array([[ 40.7812175 , -73.9643    ],
       [ 40.700635  , -74.0292275 ],
       [ 40.75080488, -73.9885725 ]])

In [17]:
index_list

TypeError: unhashable type: 'numpy.ndarray'

In [326]:
d_center = {}
d_points = {}
points_list = []
for x in range(5):
    d_center[x] = kmeans.cluster_centers_[x]
    for i in range(len(index_list[x])):
        points_list.append(cordinate_data[index_list[x][i]])
    d_points[x] = points_list
    points_list = []
d_points
d_center

{0: array([ 40.77876175, -73.9674725 ]),
 1: array([ 40.75650036, -73.98293645]),
 2: array([ 40.712375, -74.01326 ]),
 3: array([ 40.740751, -74.005415]),
 4: array([ 40.68976 , -74.045135])}

In [327]:
import numpy as pd
np.random.permutation(7)

array([2, 4, 1, 6, 5, 0, 3])

In [328]:
index_list
#while any(len(x) != 5 for x in index_list):
#index_list_sorted = sorted(index_list, key=lambda k: len(index_list[k]), reverse = True)
index_list_sorted = {}
#for sorted_key in sorted(index_list, key=lambda k: len(index_list[k]), reverse = True):
    #index_list_sorted[sorted_key] = index_list[sorted_key]
    #print(sorted_key, index_list[sorted_key])   
#index_list_sorted
order_list = sorted(index_list, key=lambda k: len(index_list[k]), reverse = True)
order_list

[1, 0, 2, 3, 4]

In [329]:
sorted(index_list, key=len)
index_list

TypeError: object of type 'int' has no len()

In [9]:
from geopy.distance import vincenty

def distance(lat1,lng1,lat2,lng2):
    add1 = (lat1,lng1)
    add2 = (lat2,lng2)
    d = vincenty(add1, add2).miles
    return d

In [387]:
#center_points = []
#center_points = kmeans.cluster_centers_
center_points

array([[ 40.77876175, -73.9674725 ],
       [ 40.75650036, -73.98293645],
       [ 40.712375  , -74.01326   ],
       [ 40.740751  , -74.005415  ],
       [ 40.68976   , -74.045135  ]])

In [40]:
def f(index_list, order_list, cordinate_data, center_points):
    for k, i in enumerate(order_list):
        n = len(index_list[i]) - 4
        for x in range(n):
            #find max distance
            d = 0
            max_index = 0
            for index in range(len(index_list[i])):
                if (d < distance(cordinate_data[index][0], cordinate_data[index][1],center_points[i][0], center_points[i][1])):
                    d = distance(cordinate_data[index][0], cordinate_data[index][1],center_points[i][0], center_points[i][1])
                    max_index = index
            #calculate minimal distance to a cluster j, j != i
            d = 10000
            min_index = 0
            for index in order_list[k+1:]:
                if (d > distance(cordinate_data[max_index][0], cordinate_data[max_index][1],center_points[index][0], center_points[index][1])):
                    d = distance(cordinate_data[max_index][0], cordinate_data[max_index][1],center_points[index][0], center_points[index][1])
                    min_index = index
            #add
            index_list[min_index].append(index_list[i][max_index])
            #delete
            del index_list[i][max_index]
        #recalculate centroids    
        center_points = []
        for j in range(3):
            cordinate_subdata = [cordinate_data[h] for h in index_list[j]]
            kmeans = KMeans(n_clusters=1, random_state=0).fit(cordinate_subdata)
            center_points.append([kmeans.cluster_centers_[0][0], kmeans.cluster_centers_[0][1]])
    return index_list, center_points

In [389]:
index_list = f(index_list, order_list, cordinate_data, center_points)


In [390]:
index_list

{0: [0, 3, 13, 18],
 1: [1, 5, 6, 8],
 2: [4, 14, 9, 17],
 3: [2, 7, 11, 12],
 4: [10, 19, 15, 16]}

In [264]:
d = 0
max_index = 0
for index in range(6):
            #print(index)
    #print(distance(cordinate_data[index][0], cordinate_data[index][1],kmeans.cluster_centers_[i][0], kmeans.cluster_centers_[i][1]))
    if (d < distance(cordinate_data[index][0], cordinate_data[index][1],kmeans.cluster_centers_[i][0], kmeans.cluster_centers_[i][1])):
        #print(d)
        d = distance(cordinate_data[index][0], cordinate_data[index][1],kmeans.cluster_centers_[i][0], kmeans.cluster_centers_[i][1])
        max_index = index
d
index_list[1][max_index]
del index_list[1][max_index]
index_list

{0: [0, 3, 13, 18],
 1: [1, 5, 6, 11, 12, 15, 16, 17, 19],
 2: [4, 14],
 3: [2, 7],
 4: [10]}

In [320]:
    center_points = []
    for j in range(5):
        cordinate_subdata = [cordinate_data[h] for h in index_list[j]]
        kmeans = KMeans(n_clusters=1, random_state=0).fit(cordinate_subdata)
        center_points.append(kmeans.cluster_centers_.tolist())
    center_points

[[[40.77876175, -73.9674725]],
 [[40.75355975, -73.98374625]],
 [[40.745936125, -73.98802825]],
 [[40.740751, -74.005415]],
 [[40.727143, -74.0223725]]]

In [275]:
cordinate_subdata = [cordinate_data[i] for i in index_list[4]]
cordinate_subdata

[[40.68976, -74.045135000000002]]

In [285]:
    for x in range(6):
        #find max distance
        d = 0
        max_index = 0
        for index in range(len(index_list[1])):
            if (d < distance(cordinate_data[index][0], cordinate_data[index][1],kmeans.cluster_centers_[1][0], kmeans.cluster_centers_[1][1])):
                d = distance(cordinate_data[index][0], cordinate_data[index][1],kmeans.cluster_centers_[1][0], kmeans.cluster_centers_[1][1])
                max_index = index
        #calculate minimal distance to a cluster , j != i
        d = 10000
        min_index = 0
        for index in order_list[1:]:
            if (d > distance(cordinate_data[max_index][0], cordinate_data[max_index][1],kmeans.cluster_centers_[index][0], kmeans.cluster_centers_[index][1])):
                d = distance(cordinate_data[max_index][0], cordinate_data[max_index][1],kmeans.cluster_centers_[index][0], kmeans.cluster_centers_[index][1])
                min_index = index
        #add
        index_list[min_index].append(index_list[1][max_index])
        #delete
        del index_list[1][max_index]
    index_list

{0: [0],
 1: [1, 5, 6, 8, 17],
 2: [4, 14, 9, 11, 12, 15, 16],
 3: [2, 7, 13, 18, 3],
 4: [10, 19, 19]}

In [159]:
from geopy.distance import vincenty

def distance(lat1,lng1,lat2,lng2):
    add1 = (lat1,lng1)
    add2 = (lat2,lng2)
    d = vincenty(add1, add2).miles
    return d

In [192]:
for i in range(5):
    print(d_points[i])
    print(d_center[i])

[[40.779429999999998, -73.963239999999999], [40.783004999999996, -73.965360000000004], [40.781321999999996, -73.973990000000001], [40.77129, -73.967299999999994]]
[ 40.77876175 -73.9674725 ]
[[40.748329999999996, -73.985680000000002], [40.758884000000002, -73.979384999999994], [40.748134999999998, -73.984800000000007], [40.758890000000001, -73.985119999999995], [40.752728000000005, -73.977230000000006], [40.75797, -73.985534999999999], [40.758735999999999, -73.978676000000007], [40.761433000000004, -73.977620000000002], [40.753093999999997, -73.981705000000005], [40.758778, -73.976939999999999], [40.764526000000004, -73.999610000000004]]
[ 40.75650036 -73.98293645]
[[40.711509999999997, -74.013319999999993], [40.713239999999999, -74.013199999999998]]
[ 40.712375 -74.01326 ]
[[40.742065000000004, -74.002530000000007], [40.739437000000002, -74.008300000000006]]
[ 40.740751 -74.005415]
[[40.68976, -74.045135000000002]]
[ 40.68976  -74.045135]


In [409]:
import codecs
f=codecs.open('plot_map.html', 'r')
print(f)

<_io.TextIOWrapper name='plot_map.html' mode='r' encoding='UTF-8'>


In [412]:
import webbrowser
new = 2
base = os.getcwd()
link = 'file://'+base+ '/plot_map.html'
webbrowser.open(link,new=new)

True